### ISSUE TITLE
removeLeadingDot does not working

### ISSUE THREAD

**Issue by freMea** [jakob101/RelativePath#17] opened 2017-07-01 11:22 UTC
VS Code version | OS | Extension version
------------------ | ---- | ----
1.13.1  | Win 10 x64 pro (french) 14393 | 0.12.0

## Steps to reproduce

1. set `"relativePath.removeLeadingDot": true`
2. insert a relative path in an HTML file

## Results

I still get the leading `./` such as for instance `<link rel="stylesheet" href="./style.css">
`

## Expectations

Only insert `style.css`

**Comment by jakob101** [comment] 2017-07-03 06:24
Hi Fred!

This is by design. If you try to find a relative path for a file 2 or more levels out, you will see that the leading dot is removed (e.g. ./../../style.css opposed to ../../style.css).

I could update the docs for this. But does it make sense for you?

**Comment by freMea** [comment] 2017-07-03 06:59
Thanks for explanation. But browsers won't load any scripts or css if in the html they are referred with a leading spot `./`. The best way would be an option to insert file as absolute path with leading `/ `referring to the root. This is the best practice to import files in html at least. But I admit the extension is called **RelativePath**, not **AnyPath** 😉

If you don't intend to add such a feature, this issue can be closed I guess.

**Comment by kristofferostlund** [comment] 2017-07-03 07:06
Perhaps that could be implemented similar to `relativePath.excludedExtensions` for extensions where `relativePath.removeLeadingDot` should be _greedy_?

**Comment by sverrejoh** [comment] 2017-07-07 09:38
Why would you ever want the leading dot in the first place? Isn't this redundant?

**Comment by kristofferostlund** [comment] 2017-07-07 09:57
I believe the main purpose for this plugin is to resolve relative file paths for js modules, where the default behavior for referencing files in the same directory is with a leading dot. [See here](https://nodejs.org/api/modules.html#modules_modules)

**Comment by sverrejoh** [comment] 2017-07-07 10:51
Yes, but both `..` and `.` is resolving in all directories, so you don't need to reference `..` via `.`. `./../foo.js` is always resolving to the same as `../foo.js`.

**Comment by kristofferostlund** [comment] 2017-07-07 10:59
The argument here is what I misunderstood with #18. The issue here is for sibling files (`./style.css` or `style.css`) where they in js should be `./foo.js`, but when linking in html it should be `<link rel="stylesheet" href="style.css">`

**Closed** 2017-07-18 18:24 UTC
